queue_rules:
  - name: default
    queue_conditions:
      - base=master
      - label~=merge-queue|dependencies
    merge_conditions:
      - check-success=tests
    merge_method: rebase

pull_request_rules:
  - name: merge using the merge queue
    conditions: []
    actions:
      queue:
