name: "Test"
on:
  pull_request:
  push:
    branches:
      - main
      - staging
      - trying
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
    - uses: cachix/install-nix-action@616559265b40713947b9c190a8ff4b507b5df49b # v31.10.4
    - run: nix build -L
