name: "Test"
on:
  pull_request:
  push:
    branches:
      - main
      - staging
      - trying
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    - uses: cachix/install-nix-action@630ae543ea3a38a9a4166f03376c02c50f408342 # v31.11.0
    - run: nix build -L
